name: CI Pipeline

on:
  push:
    branches: [main, develop]

permissions:
  contents: read
  packages: write    

jobs:
  lint-test-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: flake8 .
      - run: pytest

  sonar:
    needs: [lint-test-sonar]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para que SonarQube obtenga el historial completo de Git
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}

  build-docker:
    needs: [lint-test-sonar]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build -t ghcr.io/da2my/devops-hero:$GITHUB_SHA .
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u da2my --password-stdin
          docker push ghcr.io/da2my/devops-hero:$GITHUB_SHA